name: nvae_from_scratch
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda==12.1
  - torchmetrics
  - einops
  - kornia
  - matplotlib
  - pip
  - pip:
      - nvidia-dali-cuda120
      - tqdm
      - scheduling_utils
      - pytorch-model-summary
      - wandb
      - torch-fidelity